module.exports = {

	FILE_EXTRACTED_PARTS: {
		'CODE_IMPORTS': 'CODE_IMPORTS',
		'CODE_DEFINITION': 'CODE_DEFINITION',
		'MAP_FILE_PATH_TO_VARIABLE': 'MAP_FILE_PATH_TO_VARIABLE',
		'REQUIRED_VARIABLES': 'REQUIRED_VARIABLES',
		'REQUIRED_FILE_PATHS': 'REQUIRED_FILE_PATHS',
		'DEFINE_STATEMENT_REMOVED': 'DEFINE_STATEMENT_REMOVED'
	},

	DEFAULTS: {
		UNSET_IMPORT_VAR: '__unset__'
	}
	
};